WeatherViewControllerの責務分離
yumemi-inc/iosTraining-Reeen pull request #12
Opened 2023-07-04 07:25 UTC by reeen21

### 変更点

- WeatherViewControllerからUIViewファイルを切り出した。
- 既存のWeatherViewControllerにUIを操作するロジックを残した

### 備考
Xcode15-0-0-Betaでの実装

2023-07-07 02:18 UTC, daichikuwa0618 commented on iosTraining-Reeen/ViewContoller/WeatherViewController.swift
> +        }
[should]
VC の view すべてが `weatherView` に置き換わったのであれば、 `loadView()` で `view = weatherView` とするのが良さそうに思います。

2023-07-07 06:19 UTC, reeen21 commented on iosTraining-Reeen/ViewContoller/WeatherViewController.swift
> +        }
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/231a9034dc453876738468873c60b8ae98738889

2023-07-10 08:11 UTC, novr requested changes

2023-07-10 08:11 UTC, novr commented on iosTraining-Reeen/View/WeatherView.swift
> +    var errorAlert = UIAlertController()
[imo] errorAlertはWeatherViewが管理するべきではないです
WeatherView内に関連が一つもありません

2023-07-10 08:11 UTC, novr commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +        weatherView.reloadButton.addAction(reloadAction, for: .touchUpInside)
[imo] WeatherViewControllerがWeatherViewの内部実装に依存していることによってFatViewControllerになっています

2023-07-10 08:11 UTC, novr commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +    private var reloadButtonDelegate: ReloadButtonDelegate?
[imo] ReloadButtonDelegateを保持するのはReloadButtonになるはずです
委譲元(ReloadButton)から処理ロジックが分離できていません
WeatherViewで発生するイベントの処理を委譲するWeatherViewDelegateになるかと

2023-07-11 05:27 UTC, reeen21 commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +    private var reloadButtonDelegate: ReloadButtonDelegate?
こちらで修正しました。

新たにReloadButtonというClassを作成し、
ReloadButtonでユーザーのアクションを検出し、WeatherViewControllerのreloadButtonDidTapped(_:)でボタンが押されたときの具体的な動作を定義するように変更しました。

https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/bb15d9ced84debd54510592dbf8f1a39c53be4d2

2023-07-11 05:28 UTC, reeen21 commented on iosTraining-Reeen/View/WeatherView.swift
> +    var errorAlert = UIAlertController()
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/0828413c1a0a46e7a755fc380f536038656fa145

2023-07-11 05:33 UTC, reeen21 commented on iosTraining-Reeen/Model/ButtonDelegate.swift
> +protocol ReloadButtonDelegate: AnyObject {
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/bb15d9ced84debd54510592dbf8f1a39c53be4d にて新しくReloadButtonというビューに専念するclassを作成しました。
そのclassがViewに当てはまるのは理解できるのですが、ReloadButtonの処理を委任するDelegateメゾットは、Controllerになるという理解であっていますでしょうか。

2023-07-11 06:17 UTC, novr commented on iosTraining-Reeen/Model/ButtonDelegate.swift
> +protocol ReloadButtonDelegate: AnyObject {
MVCの時にC, ControllerはModelとView間のやり取りを受け持ちます
Viewの役割は表示とEventの受け取りです、Modelはそれ以外になります
https://developer.apple.com/library/archive/documentation/General/Conceptual/CocoaEncyclopedia/Model-View-Controller/Model-View-Controller.html#//apple_ref/doc/uid/TP40010810-CH14-SW1

今回、ReloadButtonを切り出していますがCloseButtonは作ってないですね？
TapするとActionを実行するButtonなのでパーツとして切り出すならば、ActionButtonとかになりそうです。がちょっと過剰なパーツ分けにも感じられます(ボタンを押したなら何か実行したいが、その機能はUIButtonにaddActionで用意されています

[imo] closeButtonの処理と同様な書き方で問題ないと思います
weatherViewの内部実装にWeatherViewControllerが知って(依存して)しまう点はあるのですが
```
        let reloadAction = UIAction { [weak self] _ in
            self?.weatherService.getWeatherInformation()
        }
        weatherView.reloadButton.addAction(reloadAction, for: .touchUpInside)
```

ViewとControllerを分ける場合は、WeatherViewとWeatherViewDelegateの形になると思います
WeatherViewDelegateはWeatherViewで発生するユーザイベントを定義しています

2023-07-11 06:17 UTC, novr commented on iosTraining-Reeen/Contoller/ReloadButtonDelegate.swift
> +class ReloadButtonActionImpl: ReloadButtonDelegate {
不要なclassです

2023-07-14 02:55 UTC, reeen21 commented on iosTraining-Reeen/Model/ButtonDelegate.swift
> +protocol ReloadButtonDelegate: AnyObject {
詳細にご説明頂きありがとうございます。
どのような責務分離をすべきであったか理解できました。

以下のように修正致しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/63db90f267b6d7469a19fb8efcbaa779b6f71f63

2023-07-18 01:41 UTC, novr commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +        weatherView.closeButton.addAction(closeAction, for: .touchUpInside)
[ask] reloadButtonDidTappedはdelegateで定義して、closeButtonはWeatherViewControllerで実装しているのは何故でしょうか？
どちらもweatherViewのInputで発生するイベントをWeatherViewControllerに伝えるので同じ粒度のはずです

2023-07-18 01:41 UTC, novr commented on iosTraining-Reeen/View/WeatherView.swift
> +        reloadButton.addTarget(self, action: #selector(buttonPressed), for: .touchUpInside)
[imo] addActionなら#selectorが不要です

2023-07-18 03:07 UTC, reeen21 commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +        weatherView.closeButton.addAction(closeAction, for: .touchUpInside)
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/fd446c983a5dd94dcaa5c4e8bed3fde0736f60a1

2023-07-18 03:07 UTC, reeen21 commented on iosTraining-Reeen/View/WeatherView.swift
> +        reloadButton.addTarget(self, action: #selector(buttonPressed), for: .touchUpInside)
上の部分と同時に変更致しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/fd446c983a5dd94dcaa5c4e8bed3fde0736f60a1

2023-07-18 03:09 UTC, novr approved these changes

2023-07-18 03:11 UTC, novr commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +        weatherView.minTemperatureLabel.text = weatherData.minTemperature.description
[imo] 責務分離であれば、Viewに関するコードなのでWeatherViewに移行するとよい

2023-07-18 03:22 UTC, reeen21 commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +        weatherView.minTemperatureLabel.text = weatherData.minTemperature.description
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/3b89216d8d6b066efaca37fc0b4804a1b6e956f7

2023-07-18 03:23 UTC, novr commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +        weatherView.minTemperatureLabel.text = weatherData.minTemperature.description
.アクセスが減りましたね 👍

2023-07-19 17:17 UTC, ykws commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +}
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
WeatherCondition の extension を用意する書き方もあります。
加えて、静的にバンドルされているイメージで、テストコードもあるので、 forced unwrapping してしまうのも一つの選択肢として持っておいて良いと思います。

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/optionalchaining/

```suggestion
        return condition.getImage()
    }
}

private extension WeatherCondition {
    func getImage() -> UIImage {
        switch self {
        case .sunny:
            UIImage(named: "sunny")!.withTintColor(.red)
        case .cloudy:
            UIImage(named: "cloudy")!.withTintColor(.gray)
        case .rainy:
            UIImage(named: "rainy")!.withTintColor(.blue)
        }
    }
}
```

2023-07-19 17:17 UTC, ykws commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +        let alertAction = UIAlertAction(title: "OK", style: .default, handler: nil)
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
`handler` には default value が設定されているので、 `nil` を指定する場合は省略可能です。

https://developer.apple.com/documentation/uikit/uialertaction/1620097-init

```suggestion
        let alertAction = UIAlertAction(title: "OK", style: .default)
```

2023-07-21 01:56 UTC, reeen21 commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +        if self.presentedViewController != errorAlert {
ここについては、古宮さんから頂いた[こちらのレビュー](https://github.com/yumemi-inc/iosTraining-Reeen/pull/8#discussion_r1251723243)を参考に`errorAlert`を比較対象にしていましたが、よく考えればそのpropety自体が不要なものでしたので修正します。

2023-07-21 04:08 UTC, reeen21 commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +import SnapKit
ありがとうございます！
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/1fed15139ecac442be93906b9a4e530c9bd79da9

2023-07-21 04:09 UTC, reeen21 commented on iosTraining-Reeen/View/WeatherView.swift
> +import UIKit
ありがとうございます！
上記同様にこちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/commit/1fed15139ecac442be93906b9a4e530c9bd79da9

2023-07-21 04:09 UTC, reeen21 commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +        if self.presentedViewController != errorAlert {
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/7a056e8b212861b2219beec1963053d0c41cf327

2023-07-21 04:09 UTC, reeen21 commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +        let alertAction = UIAlertAction(title: "OK", style: .default, handler: nil)
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/d37594f56ee7a8d8ce547c83d8f3a15b6a70c961

2023-07-21 04:10 UTC, reeen21 commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +        present(errorAlert, animated: true, completion: nil)
上記同様にこちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/commit/d37594f56ee7a8d8ce547c83d8f3a15b6a70c961

2023-07-21 04:10 UTC, reeen21 commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +}
なるほど
勉強になります。
こちらで変更しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/c4dadb6e0445bdcfa8eb1558891ca5a359839468

2023-07-22 06:44 UTC, ykws approved these changes
LGTM 👍

2023-07-24 09:03 UTC, daichikuwa0618 requested changes
PR の全体的な方針はとても良いと思いました。
細かい実装で気になる・修正して欲しいところがあるので、確認ください。

2023-07-24 09:03 UTC, daichikuwa0618 commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +protocol WeatherViewDelegate: AnyObject {
[must]
DIP 的な文脈ですが、この protocol を定義するべきなのは `WeatherView` 側であり、 VC からはこの protocol を参照・準拠するという関係性になっているべきかと思います。

View と VC が別モジュールに切り出されていたとしたら、と考えるといいかもしれないです。

- View 側に protocol を置いている場合
  - View は import 不要
  - VC は import 必要 (しかし、 View を参照するために import は元々必要なので、自然な依存)
- VC 側に protocol を置いている場合
  - View も import が必要 (VC が置いてあるモジュールへの import)
  - VC も import が必要 (View を置くために)
  - → module の循環参照が発生 → SPM では解決できない問題

2023-07-25 01:05 UTC, reeen21 commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +            object: nil)
こちらで修正性しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/f11146d4d1e7a92cc6717279a51bee305720dd8b

2023-07-25 01:06 UTC, reeen21 commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +        if self.presentedViewController == nil {
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/734016d79c23b0e62d1e4b427b55c55a6288c458

2023-07-25 01:12 UTC, reeen21 commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +protocol WeatherViewDelegate: AnyObject {
「Delegateの定義はViewではないし、実際のアクションの中身はControllerで定義するしそこで書くか」と考えControllerで定義してしまいました。
しかし、上記で川島さんにもご指摘いただいたように不要なmportを削除することで責務分離が分かりやすくなると思うので、以後それぞれのファイルが別のモジュールにある可能性があると考えて、実装をするようにします。
ありがとうございます🙇‍♂️

こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/641654ff91495c4d8af7657ae16ec5cb38524c53

2023-07-25 01:13 UTC, reeen21 commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +    func closeButtonDidTapped()
こちらで修正しました🙏
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/f39082f3474d0bebae2e940cf8daf258fd730d2e

2023-07-25 03:02 UTC, daichikuwa0618 commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +    func closeButtonDidTapped()
ちょっと違います。 (Delegate の命名部分、コメントが何度もあるので、もう一度参考に貼った記事や Apple の Delegate メソッドの命名を見て今一度理解されたほうが良いです。)
一度 `WeatherServiceDelegate` でいい感じに実装されています。

```swift
protocol WeatherViewDelegate: AnyObject {
    func weatherViewDidReloadButtonTapped(_ weatherView: WeatherView)
    func weatherViewDidCloseButtonTapped(_ weatherView: WeatherView)
}
```

みたいな感じになると思います。
[indexPathForPreferredFocusedView(in:) | Apple Developer Documentation](https://developer.apple.com/documentation/uikit/uitableviewdelegate/1614929-indexpathforpreferredfocusedview)
みたいな delegate に確認しに行ってるようなメソッド以外の、状況報告系のメソッドの先頭には「どこで」が必要で、先頭に `weatherView` をつけます。

2023-07-25 06:47 UTC, reeen21 commented on iosTraining-Reeen/Contoller/WeatherViewController.swift
> +    func closeButtonDidTapped()
こちらで修正しました
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/08656f07467e199378a852e03366420a3b04002b

2023-07-25 06:53 UTC, daichikuwa0618 requested changes
もう一点 🙏

2023-07-25 06:53 UTC, daichikuwa0618 commented on iosTraining-Reeen/View/WeatherView.swift
> +    func closeWeatherViewController() {
[should]
private で良さそう + `closeWeatherViewController` っていう命名は違和感あります。 (View が VC を意識している)
また、中では delegate 呼んでるだけなので、いっそのことこれらのメソッドは削除して buttons の action で直接 delegate メソッドを呼んでもいいかもしれないです。

2023-07-25 07:01 UTC, reeen21 commented on iosTraining-Reeen/View/WeatherView.swift
> +    func closeWeatherViewController() {
> いっそのことこれらのメソッドは削除して buttons の action で直接 delegate メソッドを呼んでもいいかもしれないです。

こちらで修正させて頂きました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/12/commits/4f9daf574975ee609427469f4eb52320a642224c

2023-07-25 07:06 UTC, daichikuwa0618 approved these changes
LGTM

View と VC の責務がわかれて、より見通しが良くなった印象があります！
研修にはない項目ではあるものの、よりよいコードを書こうとされてて素晴らしいです 👏

2023-07-25 07:07 UTC, reeen21 commented
ありがとうございます！

2023-07-25 07:08 UTC, merged