Delegate部分の実装
yumemi-inc/iosTraining-Reeen pull request #4
Opened 2023-06-13 02:56 UTC by reeen21

### 変更点

- `WeatherUpdateDelegate`の追加
- `reloadButton`のアクションを変更
- EmptyViewController -> WeatherViewControllerの強参照の改善 
 
 ※ `deinit()`で`WeatherViewController`が`closeButton`押下後に解放されていることを確認。

2023-06-13 05:57 UTC, daichikuwa0618 requested changes

2023-06-13 05:57 UTC, daichikuwa0618 commented on iosTraining-Reeen/APICaller.swift
> +    func didUpdateWeatherInformation(weatherInfo: String)
[must]

- delegate メソッドの命名には、ある程度決まったパターンがあり、まずはそれに則って実装するといいです。
- delegate は状況報告です。
- 参考
	- [Swift Style Guide](https://google.github.io/swift/#delegate-methods) : Google の Swift Style Guild
	- [GitHub - raywenderlich/swift-style-guide: The official Swift style guide for raywenderlich.com.](https://github.com/raywenderlich/swift-style-guide#delegates)
		- [Recommendation on delegate methods naming convention? · Issue #175 · raywenderlich/swift-style-guide · GitHub](https://github.com/raywenderlich/swift-style-guide/issues/175)
	- [Delegation in Swift | Swift by Sundell](https://www.swiftbysundell.com/articles/delegation-in-swift/)

```suggestion
protocol WeatherServiceDelegate: AnyObject {
    func weatherService(didUpdateWeatherInformation weatherInfo: String)
```

2023-06-13 05:57 UTC, daichikuwa0618 commented on iosTraining-Reeen/WeatherViewController.swift
> +    func getImage(for condition: String) -> UIImage? {
[may]
`WeatherUpdateDelegate` の extension にはその delegate メソッド以外は置かないほうが良いかなと思っています。

- どのメソッドがその protocol のメソッドかわかりやすい
- protocol への準拠を辞めるときに、消すのが楽
  - extension 部分を全部消しちゃえばいいので

2023-06-13 05:57 UTC, daichikuwa0618 commented on iosTraining-Reeen/WeatherViewController.swift
> +        (weatherService as? WeatherService)?.delegate = self
delegate への set は毎回じゃなくて一度で良いです。

2023-06-13 06:52 UTC, reeen21 commented on iosTraining-Reeen/APICaller.swift
> +    func didUpdateWeatherInformation(weatherInfo: String)
そちらの記事を参考に、`weatherConditionDidUpdate`という命名にします。

2023-06-13 06:56 UTC, reeen21 commented on iosTraining-Reeen/WeatherViewController.swift
> +        (weatherService as? WeatherService)?.delegate = self
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/4/commits/d15ee905dd69eb7856b20132762ef46598b08377

2023-06-13 06:57 UTC, reeen21 commented on iosTraining-Reeen/WeatherViewController.swift
> +    func getImage(for condition: String) -> UIImage? {
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/commit/d15ee905dd69eb7856b20132762ef46598b08377

2023-06-13 06:58 UTC, reeen21 commented on iosTraining-Reeen/WeatherViewController.swift
> +        (weatherService as? WeatherService)?.delegate = self
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/4/commits/f3855901276f1c3dd8cb407fc2ec491d6ccf495b

2023-06-13 07:06 UTC, daichikuwa0618 commented on iosTraining-Reeen/APICaller.swift
> +    func weatherConditionDidUpdate(weatherInfo: String)
自分のコメントがちゃんと伝わってなかったので補足させてください。
詳しくは共有したリンクをもう一度読んだり、 Apple の命名を参考にしてください。

- protocol の命名としては `WeatherServiceDelegate` が良いと思います。
  - `UITableViewDelegate` みたいに、 class 名 + Delegate
- delegate メソッドの命名は参考に共有した記事や Apple の API をもうちょっと読むと法則が見えてくると思います。
  - メソッド名の頭には class 名をつける: `func weatherService` から始まるということです
  - 第一引数には、情報共有する class が来る: `func weatherService(_ weatherService: WeatherServiceProtocol)` みたいな感じです
    - ちなみにこれは、 Delegate 準拠先で、情報共有してきたオブジェクトの中身を参照したいときがあるためです。
    - 例えば `func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)` でも最初の引数に `UItableView` が渡ってきてますが、これによってメソッドの中で呼び出した tableView のプロパティだったり状態を知ることができます。
  - 「何が起きたか」を知らせる
    - パラメータとして引数がある場合: 仮引数名に「何が起きたか」を命名 (例: `didSelectRowAt`)
    - 引数がない場合: メソッド名の最後につける (例: `func tableViewDidEndMultipleSelectionInteraction(_ tableView: UITableView)`)

2023-06-13 07:08 UTC, daichikuwa0618 commented on iosTraining-Reeen/WeatherViewController.swift
> +    func getImage(for condition: String) -> UIImage? {
[ask]
ちなみに、 `setupViews` の上から下に移動したのは意味がありましたか？
もし意味がなければ、余計な差分になるので、元の位置に戻してもらえると読みやすいです。

2023-06-13 07:19 UTC, reeen21 commented on iosTraining-Reeen/WeatherViewController.swift
> +    func getImage(for condition: String) -> UIImage? {
getImage(for: weatherInfo)はDelegateのプロトコル内でした使っていなかったので、場所を変えた方が中身の処理が読みやすいと判断して、変更しました。

2023-06-13 07:51 UTC, reeen21 commented on iosTraining-Reeen/APICaller.swift
> +    func weatherConditionDidUpdate(weatherInfo: String)
申し訳ないです。
そこまで汲み取ることができませんでした。
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/4/commits/da17b50741d9bb47c796c854b1339e106b37cf6e

2023-06-13 07:57 UTC, reeen21 commented on iosTraining-Reeen/WeatherViewController.swift
> +        (weatherService as? WeatherService)?.delegate = self
こちらも修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/4/commits/67a6f19e6ad43bb8934fa77a44d266bcd2ab8924

2023-06-13 08:31 UTC, daichikuwa0618 commented on iosTraining-Reeen/WeatherViewController.swift
> +    private var weatherService: WeatherServiceProtocol
[ask]
`var` への変更意図は何でしょうか？

2023-06-13 08:34 UTC, daichikuwa0618 commented on iosTraining-Reeen/APICaller.swift
> +    func weatherService(_ weatherService: WeatherServiceProtocol, conditonUpdate weatherInfo: String)
[should]
「何が起きたか」を伝えるという意味ではもうちょっと改良できそうです。
あと typo してました。 conditon → condition

```suggestion
    func weatherService(_ weatherService: WeatherServiceProtocol, didUpdateCondition weatherInfo: String)
```

ここまで書いて思ったのですが、状況としては "condition が更新 (Update) された" というよりは "condition を取得した" かなと思ったので、 `didFetchCondition` も良さそうです。

2023-06-13 08:39 UTC, daichikuwa0618 commented on iosTraining-Reeen/APICaller.swift
> +    func weatherConditionDidUpdate(weatherInfo: String)
Pull Request のやり取りにおいて、謝る必要は全く無いです。
Reviewer 側も「あーこれ自分もやっちゃうわ、わかる」と思いながら棚に上げて理想を語ってますので 😅 

今回は @reeen21 さんしかメンテナンスしないプロジェクトですが、案件だとみんなでメンテナンスしていくものなので、「わかる」と思いながら理想はこうじゃない？って感じで指摘しています。

あと、 Pull Request で指摘されると人格否定された気になるっていうのをたまに見かけますが、多分 reviewer 側は淡々とコードに対してコメントしているので、そこに人格は介入してないです。
まぁ「いっつもこの人のコードは汚いなー」とかでプロジェクト全体の品質にその人の習慣が関わるのであれば、その人のプログラミングへの考え方をプロジェクトのレベルに合わせる必要があるので、人に対する指摘をすることもありますが。

2023-06-13 08:47 UTC, reeen21 commented on iosTraining-Reeen/WeatherViewController.swift
> +    private var weatherService: WeatherServiceProtocol
`WeatherViewController.swift` 93行目にて`weatherService.delegate = self`と記述を追加した為です。

2023-06-13 08:50 UTC, daichikuwa0618 commented on iosTraining-Reeen/WeatherViewController.swift
> +    private var weatherService: WeatherServiceProtocol
class だから `let` でよくないか？と思ったんですが、 protocol ですもんね。

[should]
delegate パターンは class で使うものなので、 `WeatherServiceProtocol` は `AnyObject` にしたほうが良さそうです。
そうすれば `let` にできると思います。

2023-06-13 08:50 UTC, reeen21 commented on iosTraining-Reeen/APICaller.swift
> +    func weatherService(_ weatherService: WeatherServiceProtocol, conditonUpdate weatherInfo: String)
確かにUITableViewの`didSelectRowAt`と同様に、`conditonUpdate`よりも`didUpdateCondition`の方が見やすいなと思いました。

2023-06-13 08:58 UTC, reeen21 commented on iosTraining-Reeen/APICaller.swift
> +    func weatherConditionDidUpdate(weatherInfo: String)
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/4/commits/68b9c3e38f325010784f5a173d2a15a583a23fb2

2023-06-13 08:59 UTC, reeen21 commented on iosTraining-Reeen/WeatherViewController.swift
> +    private var weatherService: WeatherServiceProtocol
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/4/commits/68b9c3e38f325010784f5a173d2a15a583a23fb2

2023-06-13 08:59 UTC, reeen21 commented on iosTraining-Reeen/APICaller.swift
> +    func weatherService(_ weatherService: WeatherServiceProtocol, conditonUpdate weatherInfo: String)
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/4/commits/68b9c3e38f325010784f5a173d2a15a583a23fb2

2023-06-15 08:21 UTC, daichikuwa0618 requested changes

2023-06-15 08:21 UTC, daichikuwa0618 commented on iosTraining-Reeen/ModalHolderViewController.swift
> +            let weatherViewController = WeatherViewController(weatherService: WeatherService())
[should]
今、 `WeatherViewController` を作る責務が散らばっています。

- `ModalHolderViewController.viewDidAppear`
- `SceneDelegate.scene`

`ModalHolderVC` にて WeatherVC を作る必要があるのであれば、 `ModalHolderVC` にこの責務を寄せるとスッキリしそうに思いました。
また、 `WeatherVC` は `fullScreen` で表示されている = `WeatherVC` が閉じたら `ModalHodlerVC.viewDidAppear` が呼び出されることになるので、

```swift
override func viewDidAppear(_ animated: Bool) {
  super.viewDidAppear(animated)
  let weatherService = WeatherService()
  let vc = WeatherViewController(weatherService: weatherService)
  vc.modalPresentationStyle = .fullScreen
  present(vc, animated: true, completion: nil)
}
```

こんな感じの実装はどうでしょう？
こうするとプロパティによる状態管理も不要になり、実装としてはシンプルになるかなと思いました。
一度考えてみてください。

2023-06-15 08:21 UTC, daichikuwa0618 commented on iosTraining-Reeen/ModalHolderViewController.swift
>      override func viewDidAppear(_ animated: Bool) {
[must]
override したら ([loadView()](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621454-loadview) みたいにドキュメントで明示してあるものを除いて) `super` を呼びましょう。

2023-06-16 01:18 UTC, reeen21 commented on iosTraining-Reeen/ModalHolderViewController.swift
> +            let weatherViewController = WeatherViewController(weatherService: WeatherService())
ありがとうございます。

> WeatherVC は fullScreen で表示されている = WeatherVC が閉じたら ModalHodlerVC.viewDidAppear が呼び出されることになる
ここまで考えられていませんでした。

↓で修正致しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/4/commits/6c7dda1d34393245a0cce9aaa0771a380a339021

2023-06-16 02:46 UTC, daichikuwa0618 approved these changes
細かい部分の指摘なので、これを直したらマージして良さそうです。
全体的に見通しが良くていい印象を受けました。

ただ時間もあるしせっかくなので @yumemi-inc/yutu からも一度全体を見てもらってもいいかなと思いました。

2023-06-16 02:46 UTC, daichikuwa0618 commented on iosTraining-Reeen/ModalHolderViewController.swift
> +          present(vc, animated: true, completion: nil)
[must]
インデントがズレています。

2023-06-16 02:46 UTC, daichikuwa0618 commented on iosTraining-Reeen/ModalHolderViewController.swift
> +        heldViewController = nil
[must]
`heldViewController` 自体使ってないので、削除しましょう。

2023-06-16 03:47 UTC, reeen21 commented on iosTraining-Reeen/ModalHolderViewController.swift
> +          present(vc, animated: true, completion: nil)
修正しました。https://github.com/yumemi-inc/iosTraining-Reeen/pull/4/commits/2bdf2aecdd288173652f39cd0ebd8f4301663d0f

2023-06-16 07:50 UTC, daichikuwa0618 commented on iosTraining-Reeen/ModalHolderViewController.swift
> +        heldViewController = nil
@reeen21 
このコメント見逃されてる気がするので、修正お願いします 🙇

2023-06-16 07:51 UTC, reeen21 commented on iosTraining-Reeen/ModalHolderViewController.swift
> +        heldViewController = nil
こちらと同時に修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/4/commits/2bdf2aecdd288173652f39cd0ebd8f4301663d0f

2023-06-16 07:52 UTC, daichikuwa0618 commented on iosTraining-Reeen/ModalHolderViewController.swift
> +        heldViewController = nil
修正されてないですね。
プロパティ自体使われてないので、削除できます。

2023-06-16 09:34 UTC, reeen21 commented on iosTraining-Reeen/ModalHolderViewController.swift
> +        heldViewController = nil
すいません。
こちらで対応しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/4/commits/2bdf2aecdd288173652f39cd0ebd8f4301663d0f

2023-06-23 02:06 UTC, daichikuwa0618 commented on iosTraining-Reeen/ModalHolderViewController.swift
>      var heldViewController: UIViewController?
これ使ってないので削除で！

2023-06-23 02:55 UTC, merged