エラーハンドリング部分の実装
yumemi-inc/iosTraining-Reeen pull request #5
Opened 2023-06-13 09:44 UTC by reeen21

### 動作の動画

<img src=https://github.com/yumemi-inc/iosTraining-Reeen/assets/94460967/78e5f3df-16cf-48f1-b9fa-4ec2d020bc9e width="30%" />

### 変更点

- エラーをDelegateで通知して、UIAlertControllerを表示するように変更
- [YumemiWeatherError](https://yumemi-inc.github.io/ios-training/documentation/yumemiweather/yumemiweathererror/)に対応

2023-06-16 06:19 UTC, daichikuwa0618 requested changes
一度、参考資料を読み直して、設計を考えてみてください。
もちろん分からなくなったり不安になったら聞いてください。

2023-06-16 06:19 UTC, daichikuwa0618 commented on iosTraining-Reeen/APICaller.swift
> +    func weatherService(_ weatherService: WeatherService, didFailWithError error: Error)
[webView(_:didFail:withError:) | Apple Developer Documentation](https://developer.apple.com/documentation/webkit/wknavigationdelegate/1455623-webview) と命名が似てていいですね。
Apple らしい API かと思います。

```swift
optional func webView(
    _ webView: WKWebView,
    didFail navigation: WKNavigation!,
    withError error: Error
)
```

2023-06-16 06:19 UTC, daichikuwa0618 commented on iosTraining-Reeen/WeatherViewController.swift
> +import YumemiWeather
[should]
ViewController に `YumemiWeather` への依存が発生しています。

せっかく `WeatherServiceProtocol` で具体的な天気情報取得先を隠蔽したのに、結局 `YumemiWeather` であることが必須となるので、非常にもったいないと思います。

どう改善すれば ViewController に `YumemiWeather` 依存をなくせるか、考えて修正してみてください (詰まったら聞いてください)。
何か答えがあるわけではないですが、 [ios-training/Documentation/Error.md at main · yumemi-inc/ios-training · GitHub](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Error.md) の課題ドキュメントに書いてある記事や考え方は一度理解してからのほうが考えやすいかと思います。

2023-06-16 06:19 UTC, daichikuwa0618 commented on iosTraining-Reeen/WeatherViewController.swift
> +    func handleError(for error: Error) -> String {
[must]
命名とやっていることが一致していません。

- 命名: エラーをハンドリングする
- やっていること: エラーからエラーメッセージを作る

2023-06-16 07:10 UTC, reeen21 commented on iosTraining-Reeen/WeatherViewController.swift
> +import YumemiWeather
新しくEnumを作成し、`APICaller()`で`YumemiWeatherError`を判別しdelegateでVCに伝える形にしました。いかがでしょうか。
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/5/commits/78e570501adf6ccf3abca0efb3a9c8971eb58206

2023-06-16 07:14 UTC, daichikuwa0618 commented on iosTraining-Reeen/WeatherViewController.swift
> +import YumemiWeather
良いと思います！

[should]
`} catch {` で print だけしかしておらず、エラーに気づきにくい状態になっているのだけもったいないと思います。

- YumemiWeather の作り的にここでは絶対 catch されないのであれば `assertionFailure` 等で落とす
- 起こり得るなら `WeatherError` に case を追加する

といった感じにするともっと良くなりそうです！

2023-06-16 07:20 UTC, reeen21 commented on iosTraining-Reeen/WeatherViewController.swift
> +import YumemiWeather
- YumemiWeather の作り的にここでは絶対 catch されないのであれば assertionFailure 等で落とす

こちらを採用します！

2023-06-16 07:23 UTC, reeen21 commented on iosTraining-Reeen/WeatherViewController.swift
> +import YumemiWeather
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/5/commits/0f711628c6ccdc3b01c529ec1a2afd70d6f460d4

2023-06-16 07:30 UTC, daichikuwa0618 commented on iosTraining-Reeen/APICaller.swift
> +            assertionFailure("error occurred in getWeatherInformation().")
[should]
`getWeatherInformation` でエラーが起きたっていうのはコードを読めばすぐわかる情報なので、ここでは

- 実装時に想定されてないエラーであること
- もしエラーが起きたならどこに問題があるかの可能性を示す (例えば YumemiWeather のアップデートで仕様が変わったとか)

辺りの情報がほしいです。
こういうデバッグ用メッセージやコメントにはコードからは直ぐには読み取れない背景や情報を書くといいと思います。

2023-06-16 07:30 UTC, daichikuwa0618 reviewed
もうほぼほぼ違和感ないですが、細かいところをコメントしました。

2023-06-16 08:01 UTC, reeen21 commented on iosTraining-Reeen/WeatherError.swift
> +    func errorMessage() -> String {
下の部分も含め、修正しました。
LocalizedErrorに準拠して書けること知らなかったので勉強になりました。
ありがとうございます。

https://github.com/yumemi-inc/iosTraining-Reeen/pull/5/commits/08b1e0d83147c9b74d1db5c5b2835242190fe471

2023-06-23 02:17 UTC, daichikuwa0618 approved these changes
良さそうです！

2023-06-30 03:06 UTC, merged