Json部分の実装
yumemi-inc/iosTraining-Reeen pull request #6
Opened 2023-06-16 05:27 UTC by reeen21

### 動作画像
<img src=https://github.com/yumemi-inc/iosTraining-Reeen/assets/94460967/7e98443a-2b54-4891-9fa3-64c1a6c03553 width="25%" />
<img src=https://github.com/yumemi-inc/iosTraining-Reeen/assets/94460967/7b897343-199c-4a7b-a3ec-934aa4330625 width="25%" />
<img src=https://github.com/yumemi-inc/iosTraining-Reeen/assets/94460967/a544d2e1-10c0-4bf5-988f-9f74248a72f7 width="25%" />

### 変更点

- WeatherDataと言う構造体を定義し、そこにAPIからのデータを格納した
- convertFromSnakeCaseを使用して、構造体のそれぞれの値の可読性を向上させた
- 最高気温/最低気温のラベルに情報を入れた

2023-06-16 06:26 UTC, daichikuwa0618 reviewed
#5 の修正に引っ張られそうな気がしているので、設計的な部分は後でまた見ます 🙇

2023-06-16 06:26 UTC, daichikuwa0618 commented on iosTraining-Reeen/APICaller.swift
> +            let jsonString = "{\"area\": \"tokyo\", \"date\": \"2020-04-01T12:00:00+09:00\"}"
[FYI]
Extended string delimiters を使うとエスケープが不要になります。

```suggestion
            let jsonString = #"{"area": "tokyo", "date": "2020-04-01T12:00:00+09:00"}"#
```

参考: [Swift の文字列リテラルにおける特殊文字のエスケープ - Qiita](https://qiita.com/daichidaiji/items/9b1179ae32d160292826)

2023-06-16 08:27 UTC, reeen21 commented on iosTraining-Reeen/APICaller.swift
> +            let jsonString = "{\"area\": \"tokyo\", \"date\": \"2020-04-01T12:00:00+09:00\"}"
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/6/commits/c3129f1aee66a20076cf4b648f7ed7a3ebacd607

2023-06-30 09:44 UTC, novr requested changes

2023-06-30 09:44 UTC, novr commented on iosTraining-Reeen/Model/APICaller.swift
> +//  APICaller.swift
[MUST] ファイルとヘッダーの内容があっていません

2023-06-30 09:44 UTC, novr commented on iosTraining-Reeen/Model/WeatherData.swift
> +struct WeatherData: Codable {
[nits] decodeしか行わないのでDecodableで十分です

2023-06-30 09:44 UTC, novr commented on iosTraining-Reeen/Model/APICaller.swift
> +    func weatherService(_ weatherService: WeatherService, didFailWithError error: LocalizedError)
[ASK] weatherServiceがWeatherServiceProtocolで揃っていない理由はありますか？

2023-06-30 09:44 UTC, novr commented on iosTraining-Reeen/Model/APICaller.swift
> +    func weatherService(_ weatherService: WeatherService, didFailWithError error: LocalizedError)
[MUST] Domainのエラーでない場合は、特定のLocalizedErrorでなくErrorで定義しましょう
LocalizedErrorに準拠して、errorDescriptionを実装していればError型のlocalizedDescriptionで受け取れます

2023-06-30 13:11 UTC, ykws commented on iosTraining-Reeen/Model/APICaller.swift
> +                throw WeatherError.weatherDataNotExist
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)
WeatherError なので、 case の名前として weather が冗長に感じました。

![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
ここで例外が発生するのはデータがないからでしょうか？
違う要因があって、結果データがないように感じました。
他の case は理由だと思うので、揃えることができそうか（同じ Error の型として扱って良いのか）
もし揃えるのが難しい場合、違う Error の型として定義する選択肢もあると感じました。

2023-07-04 01:29 UTC, reeen21 commented on iosTraining-Reeen/Model/APICaller.swift
> +    func weatherService(_ weatherService: WeatherService, didFailWithError error: LocalizedError)
編集ミスでした。
`WeatherServiceProtocol`の統一しました。

2023-07-04 01:33 UTC, reeen21 commented on iosTraining-Reeen/Model/APICaller.swift
> +                throw WeatherError.weatherDataNotExist
> WeatherError なので、 case の名前として weather が冗長に感じました。

`dataNotExistsError`という命名に変更しました。  
  

> ここで例外が発生するのはデータがないからでしょうか？
> 違う要因があって、結果データがないように感じました。
> 他の case は理由だと思うので、揃えることができそうか（同じ Error の型として扱って良いのか）
> もし揃えるのが難しい場合、違う Error の型として定義する選択肢もあると感じました。

エンコードに失敗する場合に特化した`encodingConversionError`を定義しました。
また全てのエラーの命名に一貫性が出るように命名を下記のように変更しました。
```
case invalidParameterError
case unknownError
case dataNotExistsError
case encodingConversionError
```

2023-07-04 01:34 UTC, reeen21 commented on iosTraining-Reeen/Model/APICaller.swift
> +//  APICaller.swift
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/6/commits/c1cdb1025474d7fcd9a3bc98f80030fe9763fe4b

2023-07-04 01:34 UTC, reeen21 commented on iosTraining-Reeen/Model/WeatherData.swift
> +struct WeatherData: Codable {
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/6/commits/c1cdb1025474d7fcd9a3bc98f80030fe9763fe4b

2023-07-04 01:34 UTC, reeen21 commented on iosTraining-Reeen/Model/APICaller.swift
> +    func weatherService(_ weatherService: WeatherService, didFailWithError error: LocalizedError)
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/6/commits/c1cdb1025474d7fcd9a3bc98f80030fe9763fe4b

2023-07-04 01:35 UTC, reeen21 commented on iosTraining-Reeen/Model/APICaller.swift
> +    func weatherService(_ weatherService: WeatherService, didFailWithError error: LocalizedError)
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/6/commits/c1cdb1025474d7fcd9a3bc98f80030fe9763fe4b

2023-07-04 01:35 UTC, reeen21 commented on iosTraining-Reeen/Model/APICaller.swift
> +                throw WeatherError.weatherDataNotExist
こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/6/commits/c1cdb1025474d7fcd9a3bc98f80030fe9763fe4b

2023-07-04 04:12 UTC, reeen21 commented on iosTraining-Reeen/ViewContoller/WeatherViewController.swift
>          let errorAlert = UIAlertController(title: "Alert", message: error.errorDescription, preferredStyle: .alert)
@novr 
こちらで修正致しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/6/commits/38f3cc19362cde62fa6d19440643d36ebafcc892

2023-07-04 04:14 UTC, novr commented on iosTraining-Reeen/Model/WeatherService.swift
> +extension WeatherService: LocalizedError {
[ASK] WeatherServiceがLocalizedErrorに準拠されているのはなぜでしょうか？

2023-07-04 04:21 UTC, reeen21 commented on iosTraining-Reeen/Model/WeatherService.swift
> +extension WeatherService: LocalizedError {
上記レビューの部分で読み間違えていました🙏
再度修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/6/commits/ee0f2b82b818f776aa10a8c47cb3056751e317e9

2023-07-04 04:23 UTC, novr approved these changes

2023-07-04 19:24 UTC, ykws approved these changes
LGTM 👍

2023-07-04 19:24 UTC, ykws commented on iosTraining-Reeen/Model/WeatherService.swift
> +    func getWeatherInformation() {
![next-badge](https://img.shields.io/badge/review-next-blueviolet)
API の命名について、今回の変更点ではないのでスコープ外ですが、直接 WeatherInformation を取得するわけではないので get は避けた方が驚きが少ないです。

- #4 

Delegate の実装のタイミングで直接取得する形ではなくなったので、そのタイミングで rename できると良さそうでした。
具体的には、 fetch とか request とかのイメージです。

[Delegateパターン](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Delegate.md) にも記載した CLLocationManager の [requestLocation()](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620548-requestlocation) が一例です。

2023-07-07 01:00 UTC, merged