NotificationCenterの部分の修正
yumemi-inc/iosTraining-Reeen pull request #8
Opened 2023-06-16 09:25 UTC by reeen21

### 変更点

- `UIApplication.willEnterForegroundNotification`でアプリがフォアグラウンドに戻ってくるタイミングを監視
- `errorAlert.dismiss(animated: true)`でエラーが出ている時も消えるようにした

2023-06-30 09:56 UTC, novr requested changes

2023-06-30 09:56 UTC, novr commented on iosTraining-Reeen/ViewContoller/WeatherViewController.swift
> +    private let notificationCenter = NotificationCenter()
[must] 不要です

2023-06-30 09:56 UTC, novr commented on iosTraining-Reeen/ViewContoller/WeatherViewController.swift
> +        errorAlert.dismiss(animated: true)
[ASK] 復帰時にエラーが消えてしまうのはユーザフレンドリーでしょうか？

2023-07-04 04:40 UTC, reeen21 commented on iosTraining-Reeen/ViewContoller/WeatherViewController.swift
> +        errorAlert.dismiss(animated: true)
> エラーが表示された状態での動きも確認してみましょう

この部分を「復帰時にエラーのアラートが消えて天気予報が更新されるようにするべき」というように解釈していました。

2023-07-04 04:55 UTC, reeen21 commented on iosTraining-Reeen/ViewContoller/WeatherViewController.swift
> +        errorAlert.dismiss(animated: true)
こちらで修正しました。https://github.com/yumemi-inc/iosTraining-Reeen/pull/8/commits/86963fd7059336ee111ccdde0469f6678bf4d414
また、エラーが出ている際に天気情報が更新されるのもおかしいので、`UIAlertController`が表示されていない時のみ`weatherService.getWeatherInformation()`を呼ぶように変更しました。

2023-07-04 06:44 UTC, novr commented on iosTraining-Reeen/ViewContoller/WeatherViewController.swift
> +        if !(UIViewController.topMostViewController is UIAlertController) {
[imo] sceneから取らなくても自分がpresentしているViewControllerはpresentedViewControllerで取得できます
https://developer.apple.com/documentation/uikit/uiviewcontroller/1621407-presentedviewcontroller

2023-07-04 08:46 UTC, reeen21 commented on iosTraining-Reeen/ViewContoller/WeatherViewController.swift
> +        if !(UIViewController.topMostViewController is UIAlertController) {
`presentedViewController`初めて知りました。
こんな便利なメゾットがあるのですね。
とても勉強になりました。

こちらで修正しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/8/commits/de10ed7c22f613f418ec0177ef94ff9ad95a854b

2023-07-04 09:03 UTC, novr commented on iosTraining-Reeen/ViewContoller/WeatherViewController.swift
> +        if !(UIViewController.topMostViewController is UIAlertController) {
topMostViewControllerでもpresentedViewController使っていますね
コード例など参照する場合、どうして動くのか？を意識してみましょう

2023-07-04 10:55 UTC, reeen21 commented on iosTraining-Reeen/ViewContoller/WeatherViewController.swift
> +        if !(UIViewController.topMostViewController is UIAlertController) {
以後気をつけます🙇‍♂️

2023-07-04 11:03 UTC, reeen21 commented on iosTraining-Reeen/ViewContoller/WeatherViewController.swift
> +    static var topMostViewController: UIViewController? {
こちらで削除致しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/8/commits/73a14707fa45c1aefb278d84dbc8887aff83ff2d

2023-07-04 11:04 UTC, reeen21 commented on iosTraining-Reeen/ViewContoller/WeatherViewController.swift
> +        if (self.presentedViewController == nil) {
こちらで変更しました。
https://github.com/yumemi-inc/iosTraining-Reeen/pull/8/commits/e627d15aa8147c20c5f723d3213a93201aaf7529

2023-07-04 11:30 UTC, novr approved these changes

2023-07-07 01:02 UTC, merged